### ISSUE TITLE
consider adding a CITATION.cff

### ISSUE THREAD

**Issue by egonw** [mcsorkun/ChemPlot#11]
... that makes the link to your research paper machine readable. See https://citation-file-format.github.io/

**Comment by mcsorkun** [comment]
@egonw it would definitely be useful, thanks!

**Comment by dajtmullaj** [comment]
Done! 
Added in BibTex format since preferably the paper we wrote should be cited when acknowledging the use of the software.

**Comment by egonw** [comment]
yes, that works. In a `CITATION.cff` you can do this too, btw. See how I did it here: https://github.com/egonw/bacting/blob/main/CITATION.cff#L12-L25
