### ISSUE TITLE
ImportError: cannot import name 'Panel' from 'bokeh.models'

### ISSUE THREAD

**Issue by cjvsimoes** [mcsorkun/ChemPlot#13]
Hi!

Has anyone had trouble importing "Panel" from bokeh.models (err msg copied below)?

Thnx!

>>> from chemplot import Plotter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/applic/ChemPlot/chemplot/__init__.py", line 1, in <module>
    from .chemplot import Plotter
  File "/data/applic/ChemPlot/chemplot/chemplot.py", line 26, in <module>
    from bokeh.models import ColorBar, HoverTool, Panel, Tabs
ImportError: cannot import name 'Panel' from 'bokeh.models' (/data/miniconda3/envs/chemplot_env/lib/python3.9/site-packages/bokeh/models/__init__.py)

**Comment by dajtmullaj** [comment]
Hi @cjvsimoes ,
Can you share the list of dependencies you installed? Specifically the version of bokeh you are using in your environment.

**Comment by dajtmullaj** [comment]
The latest released version of Bokeh changed Panel for TabPanel. I think that might be the issue. 
For the moment can you try using Bokeh up to version 2.4.3?

**Comment by cjvsimoes** [comment]
It worked.
Thanks!
