### ISSUE TITLE
Some problems to run chemplot on google colab

### ISSUE THREAD

**Issue by xoolCCG** [mcsorkun/ChemPlot#14]
Good day team chemplot!
I write because a have some problems to run chemplot on google colab. I installed the necessary software to run chemplot but the following code did not run. 

Do you have any idea what happen?. 

Thanks very much for information and help me,

**Comment by mcsorkun** [comment]
Hello @xoolCCG 

I just checked your notebook, there were several problems with it. 
- Wrong path for your data
- Wrong parameter "target", you don't have any target only your data so you cannot use tailored similarity.
- Also there was some matplotlib version problem from ChemPlot side I will create another issue for it.

Now, I updated your code, it is working. By changing parameters/methods you can play with your data.

**Comment by mcsorkun** [comment]
Also ref documents are available here: https://chemplot.readthedocs.io/en/latest/
And the paper: https://chemistry-europe.onlinelibrary.wiley.com/doi/10.1002/cmtd.202200005

**Comment by xoolCCG** [comment]
hello! mcsorkun,

Thank you very much for your time and information. The result is great after I use the information tha you shared.

Best regard
