### ISSUE TITLE
Tanimoto metric 

### ISSUE THREAD

**Issue by jessielyons** [mcsorkun/ChemPlot#15]
Hi,

I am slowly learning chemplot. Is it possible to compare the tsne generated from chemplot with tanimoto distance based tsne and use your interactive visualization? Please guide.

thanks,
Jessie

**Comment by mcsorkun** [comment]
Hello @jessielyons ,

Yes, it is possible to compare the distances of molecules. Chemplot uses 3 different dimensionality reduction methods: t-SNE, UMAP, and PCA. The first two are non-linear clustering algorithms, therefore comparing distances may not always end up with meaningful results. However, PCA is linear and could be a good option. 

After dimensionality reduction is applied, the method returns reduced coordinates (x and y) of each molecule. Basically, you can calculate the euclidian distance of every molecule couple root(xˆ2+yˆ2). For Tanimoto distance, you can extract the binary fingerprints (several exists in RdKit) and then calculate the Tanimoto/Jaccard distance of these molecules. Then you can make an analysis by comparing these distances.

I hope it helps!

**Comment by jessielyons** [comment]
Dear @mcsorkun ,

Thanks so much for your reply. Sorry I perhaps wasn't clear. I know how to calculate Tanimoto distance. I do not know how to use the calculated Tanimoto distance to display via your interactive map.  Can you please share your example via chemplot how we can use Tanimoto distance to generate the umap and use chemplot to see the interactive map? Any example would do. 

Apologies if it is very time consuming question for you. I am not a chemist and really like your chemplot software to better understand and use it in a comprehensive manner with metrics like Tanimoto distance that I am more familiar with. It can also allow we to compare and understand your distance priority relation metric with Tanimoto. Thanks a ton for your help in advance.

**Comment by mcsorkun** [comment]
Hello @jessielyons,

Tanimoto distance is calculated from high dimensions (e.g 1024 sized FP), therefore you cannot visualize high-dimensional distance in 2-dimension.
