### ISSUE TITLE
Some problems to run t-SNE in the APP

### ISSUE THREAD

**Issue by xoolCCG** [mcsorkun/ChemPlot#17]
Hello Chemplot team!.

I write because only can run UMAP and PCA in the APP. Any recomendation for run t-SNE in the APP.

Thank you very much for help me,

**Comment by dajtmullaj** [comment]
@xoolCCG I am assuming you are referring to the ChemPlot Streamlit webapp (https://chemplot.streamlit.app/). 
t-SNE can require extensive time to finish its computations. Hence for complex use cases we recommend using the library. The web app is for more lightweight use cases.
