### ISSUE TITLE
Using similarity type "structural" throws AttributeError if using t-SNE

### ISSUE THREAD

**Issue by mrcblt** [mcsorkun/ChemPlot#23]
When using similarity type 'structural' together with t-SNE, an `AttributeError: 'list' object has no attribute 'shape'` is thrown. Code to reproduce the error:

```python
from chemplot import Plotter, load_data

data_BBBP = load_data("BBBP")
cp_BBBP = Plotter.from_smiles(data_BBBP["smiles"], target=data_BBBP["target"], target_type="C", sim_type="structural")
cp_BBBP.tsne()
```

I will be submitting a pull request for a proposed fix shortly.

**Comment by alfredoq** [comment]
Hello, 
I am facing this problem too. Was it possible to fix the code to accept the 'structural' keyword?
Thank you very much in advance for the support!

best regards

**Comment by mrcblt** [comment]
Hello Alfredo,

Unfortunately, my pull request has not been merged yet, and the last change to this code repository was in September 2022. However, if you are using `chemplot=1.2.1` with `python=3.9` and `bokeh=2.4.3`, the example in my original post actually works. If you have to use Python 3.10 and therefore `chemplot=1.2.0`, you can use the following workaround:

```python
from chemplot import Plotter, load_data

class FixedPlotter(Plotter):
    def _Plotter__data_scaler(self):
        if self._Plotter__sim_type != "structural":
            return StandardScaler().fit_transform(self._Plotter__df_descriptors.values)
        return self._Plotter__df_descriptors.values

data_BBBP = load_data("BBBP")
cp_BBBP = FixedPlotter.from_smiles(data_BBBP["smiles"], target=data_BBBP["target"], target_type="C", sim_type="structural")
cp_BBBP.tsne()
```

Hope this helps.

**Comment by alfredoq** [comment]
Hello Marcel,
Thank you very much for suggesting this workaround! it worked as expected,
kind regards

Alfredo
