### ISSUE TITLE
Installation issues: matplotlib; sklearn

### ISSUE THREAD

**Issue by Prospero1988** [mcsorkun/ChemPlot#25]
Hi!

When trying to install with pip, I get errors with the matplotlib and scikit-learn libraries, even though both are installed and up to date.
At the bottom, I paste the fragment of the entire output from the console, where the errors occur. The whole output is attached as a txt file. I have no idea what to do with this problem. I'm using PowerShell with system administrator privileges. RDkit is installed and activated.

[chemplot_install_error.txt](https://github.com/mcsorkun/ChemPlot/files/11652503/chemplot_install_error.txt)

     `Extracting freetype-2.6.1.tar.gz
      Building freetype in build\freetype-2.6.1
      msbuild build\freetype-2.6.1\builds\windows\vc2010\freetype.sln /t:Clean;Build /p:Configuration=Release;Platform=x64
      error: command 'msbuild' failed: None
      [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for matplotlib`

      error: could not create 'build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-          
      australian-limit-2-data_version-1-status-deactivated.json.gz': No such file or directory
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> D:\Users\aleniak\AppData\Local\Temp\pip-install-1uih_fd0\scikit-learn_a2e09175a0394b6b907b9332707bf76e\build\temp.win-amd64-cpython-310\Release\ccompiler_opt_cache_ext.py
      INFO:
      ########### CLIB COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> D:\Users\aleniak\AppData\Local\Temp\pip-install-1uih_fd0\scikit-learn_a2e09175a0394b6b907b9332707bf76e\build\temp.win-amd64-cpython-310\ccompiler_opt_cache_clib.py
      [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for scikit-learn
    Failed to build matplotlib scikit-learn
    ERROR: Could not build wheels for matplotlib, scikit-learn, which is required to install pyproject.toml-based projects`

**Comment by JacksonBurns** [comment]
I have added support for modern versions of Python in the linked PR.
