### ISSUE TITLE
unexpected attribute 'plot_width' to figure,

### ISSUE THREAD

**Issue by khoroshyy** [mcsorkun/ChemPlot#27]
I get this error.
cp_BACE.interactive_plot(show_plot=True)
Any idea what is the problem?

'''python
{
	"name": "AttributeError",
	"message": "unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 cp_BACE.interactive_plot(show_plot=True)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/chemplot/chemplot.py:542, in Plotter.interactive_plot(self, size, kind, remove_outliers, is_colored, clusters, filename, show_plot, title)
    540 tabs = None
    541 if kind == \"scatter\":
--> 542     p, tabs = self.__interactive_scatter(x, y, df_data, size, is_colored, clusters, title)
    543 else: 
    544     p = self.__interactive_hex(x, y, df_data, size, title)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/chemplot/chemplot.py:626, in Plotter.__interactive_scatter(self, x, y, df_data, size, is_colored, clusters, title)
    623     TOOLTIPS = parameters.TOOLTIPS_TARGET
    625 # Create plot
--> 626 p = figure(title=title, plot_width=size, plot_height=size, tools=tools, tooltips=TOOLTIPS)
    628 if len(self.__target) == 0 or not(is_colored):
    629     p.circle(x=x, y=y, size=2.5, alpha=0.8, source=df_data)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/bokeh/plotting/_figure.py:195, in figure.__init__(self, *arg, **kw)
    193 for name in kw.keys():
    194     if name not in names:
--> 195         self._raise_attribute_error_with_matches(name, names | opts.properties())
    197 super().__init__(*arg, **kw)
    199 self.x_range = get_range(opts.x_range)

File ~/bin/miniconda39/envs/cheminfo/lib/python3.12/site-packages/bokeh/core/has_props.py:375, in HasProps._raise_attribute_error_with_matches(self, name, properties)
    372 if not matches:
    373     matches, text = sorted(properties), \"possible\"
--> 375 raise AttributeError(f\"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}\")

AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width"
}
'''

**Comment by khoroshyy** [comment]
Issue fixed by downgrading bokeh for version lower than 3.0

**Comment by JacksonBurns** [comment]
I have resolved this issue for bokeh 3 in the linked PR.
