### ISSUE TITLE
Google Colab: Pip Install Error

### ISSUE THREAD

**Issue by Nickspizza001** [mcsorkun/ChemPlot#28]
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by JacksonBurns** [comment]
I have resolved this issue in the linked PR.
